### ISSUE TITLE
hw03 dbernhard tests: bitcast_{1,3,4} should not pass

### ISSUE THREAD

**Issue by da-gazzi** [nicdard/compiler-design-eth-tests#22]
The `bitcast_1`, `bitcast_3` and `bitcast_4` tests use the `i8` type, which is specified to be not part of LLVMLite - LLVMLite only supports `i8*` pointers according to the documentation on moodle...

**Comment by dbernhard-0x7CD** [comment]
You're right. I'll fix them :+1:

**Comment by nicdard** [comment]
@dbernhard-0x7CD I just merged your PR since we are running out of time, however I would prefer to still have some tests with i8* type. I would say that to provide a meaningful test with i8* we should for example setting up a global string, then maybe index in it with a gep, which would retrieve an i8*, then convert the pointer with a bitcast to i64* and load a full quadword from memory. At this point either shift the result to take only first character or return the full quadword if the memory we load was initialiased already (since gep allows out of bound indexing).

What do you think? Unfortunately I am having lessons now that's why I am asking (currently from mobile) :)
